name: anya

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  anya:
    if: |
      github.event.comment.user.login != 'anya-research' &&
      github.event.comment.user.login != 'yuki-fuyutsuki' &&
      (startsWith(github.event.comment.body, '/anya') ||
      contains(github.event.comment.body, ' /anya')) &&
      !contains(github.event.comment.body, '/anya review')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run Anya
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.ANYA_TOKEN }}
        with:
          model: opencode/muse-spark-1.2-contributor-free
          use_github_token: true
          mentions: "/anya"
          share: false
