name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  draft:
    if: github.repository == 'Cyrax321/SNAGLINE'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
